#!/bin/bash


# Ported to use "fswatch" (https://github.com/alandipert/fswatch)
# install details at http://stackoverflow.com/a/13807906


# Watch all *.go files in the specified directory
# Call the restart function when they are saved
function monitor() {
    fswatch $1 "echo '>> Reloading...' && go run $FILE_PATH &"
}

# Make sure all background processes get terminated
function close {
    killall -9 fswatch
    killall -9 go-reload
    exit 0
}

trap close INT
echo "== Go-reload"
echo ">> Watching directories, CTRL+C to stop"

FILE_PATH=$1
FILE_NAME=$(basename $FILE_PATH)
PROCESS_NAME=${FILE_NAME%%.*}

# Start the main Go program
go run $FILE_PATH &

# Monitor the /src directories in all directories on the GOPATH
OIFS="$IFS"
IFS=':'
for path in $GOPATH
do
    echo "PATH: " $path
    monitor $path/src &
done
IFS="$OIFS"

# Monitor the current directory
monitor .